### ISSUE TITLE
Did you consider using fine-tuned IVLP as frozen VL features provider?

### ISSUE THREAD

**Issue by SuperbTUM** [muzairkhattak/PromptSRC#11]
Hello. First of all, thanks for your hard work! I read your paper and saw you used the original CLIP model to produce frozen VL features for self-consistency loss. Have you ever tried other CLIP-variants such as the ImageNet-trained IVLP model to see if there is a better PromptSRC performance? Thanks!

**Comment by muzairkhattak** [comment]
Hi @SuperbTUM,

Thank you for showing interest in PromptSRC and sorry for the delayed response. 

Regarding your query, I think we have not tried to use other CLIP variants like fine-tuned IVLP to produce the frozen features. 

In our understanding, the frozen features should be as general (task agnostic) as possible, so the original CLIP model would be more suitable, as compared to other variants like IVLP, which are focused on only imagenet (leading to task-specific features).

I hope this helps! Kindly let us know if there are any other questions.

Thank you and kind regards!

**Comment by muzairkhattak** [comment]
Hi @SuperbTUM,

I am closing the issue for now. Feel free to reopen it incase you still have any question.

Thank you and kind regards!
