### ISSUE TITLE
What does the perfomance% refers to?

### ISSUE THREAD

**Issue by ChushanZhang** [muzairkhattak/PromptSRC#12]
Hi there,

Thank you for your work!

I have a quick question regarding Figure 2 in your main paper: What does the performance percentage refer to? Generally, I understand your points about it relating to novel-set performance, but does this apply to the 11 overall datasets or a specific one?

Could you kindly guide me on this?

Thank you!

**Comment by muzairkhattak** [comment]
Hi @PoopBear1,

Thank you for showing interest in PromptSRC!

Regarding your query, the performance percentage refers to the performance averaged over all 11 datasets. 

I hope that is helpful.
Thank you and kind regards!
