### ISSUE TITLE
Detailed configuration of maple in few shot k=1,2,4,8,16 Or maple's detailed result data

### ISSUE THREAD

**Issue by dana-niu** [muzairkhattak/PromptSRC#14]
Hello, 
I noticed what you said in few shot K = 1, 2, 4, 8 and 16, "Prompt src performance comparison in fever-shot image recognition setting. All methods are trained on vit-b/16 clip backbone.
Using their best settings. "You can't see the final detailed result data of each experiment in this chart.
Can you tell me the detailed configuration of maple in this experiment?
Or can you give the detailed result data of maple?
Thank you very much.

**Comment by muzairkhattak** [comment]
Hi @dana-niu,

Thank you for showing interest in PromptSRC. 

For the per-dataset results in few-shot settings, you can kindly refer to Tab. 13 (in the appendix) of the paper where all results have been provided. 

Let us know if you need any further help. 

Kind regards!

**Comment by dana-niu** [comment]
I'm very sorry I didn't notice the last form.
Thank you very much for your patient reply.
Your reply was very helpful.
