### ISSUE TITLE
Inquiry About Script for Domain Generalization Experiment

### ISSUE THREAD

**Issue by wdi-nancy** [muzairkhattak/PromptSRC#16]
Thank you for your excellent work on this repository. I have been thoroughly studying your paper, particularly the domain generalization experiments, and I have found it incredibly insightful.

I am currently trying to reproduce the domain generalization experiment described in your paper. Could you please clarify which script file is used for this experiment? Specifically, I would like to know if the `xd-train` script is the one employed for the domain generalization experiment, or if there is another script I should be using.

Your guidance would be immensely helpful.

Thank you in advance for your assistance.

**Comment by muzairkhattak** [comment]
Hi @wdi-nancy,

Thank you for showing interest in our work!

Regarding your query, yes you are right, we use `xd-train` script for training the model for domain generalization experiments.
