### ISSUE TITLE
Question about the hyper-parameter ablation in the GPA component

### ISSUE THREAD

**Issue by auniquesun** [muzairkhattak/PromptSRC#17]
@muzairkhattak Thanks for sharing the paper and code. It's a great work!

I encounter a problem when trying to change the hyper-paramters in the GPA component. 

Specifically, the hyper-parameters are mean and variance of a gaussian distribution. The experiments are conducted on the base-to-new benchmark. When ablating the mean variable, the candidate values are 7,9,11,13,15 and I keep variance=1 by default. When ablating the variance variable, the candidate values are 1,3,5,7,9 and I keep mean=15 by default. 

However, after running the experiments, I found all runnings produced same accuracies on the base and new classes. I am sure I have changed the mean and variance through commad line arguments, e.g. TRAINER.PROMPTSRC.GPA_MEAN ${GPA_MEAN},         TRAINER.PROMPTSRC.GPA_STD ${GPA_STD}.

I am confused by this problem for a while. Now I wonder whether the GPA component can work. Do you have any suggestions? Thanks.

**Comment by muzairkhattak** [comment]
Hi @auniquesun,

Thank you for showing interest in PromptSRC! 

Regarding your question, I think the GPA component works indeed. We have reported ablation results about GPA Hyperparameters in Table 6 in the [paper's supplementary material](https://arxiv.org/pdf/2307.06948). 

For your case, can you check by debugging (e.g printing) if the GPA values are properly set from the command line arguments into the main code? 

Additionally, you can also check by explicitly setting the values of GPA [in the config file directly here. ](https://github.com/muzairkhattak/PromptSRC/blob/main/configs/trainers/PromptSRC/vit_b16_c2_ep20_batch4_4%2B4ctx.yaml)

I hope by debugging we can clarify the issues.
Let me know if that works well for you.

Thank you and kind regards!

**Comment by auniquesun** [comment]
@muzairkhattak Thanks for your reply. I will try  it.

**Comment by muzairkhattak** [comment]
Hi @auniquesun,

I hope the issue has been resolved. 
I am closing this issue and please feel free to reopen if there are still any questions. 

Thank you!
