### ISSUE TITLE
Question about how to get Figure 2

### ISSUE THREAD

**Issue by cheny02** [muzairkhattak/PromptSRC#18]
Hi there,

Thank you for your work!

I have question about Figure 2 in your main paper. How to get the novel performance of each epoch?

**Comment by muzairkhattak** [comment]
Hi @Chenyyyyyyyyy,

Thank you for showing interest in PromptSRC!

Sorry for the delayed response. In that figure, we only train and evaluate models at 5, 10, 15, and 20 epochs. We do not train and test models at each epoch.

I hope that is helpful.

Thank you and kind regards!

**Comment by cheny02** [comment]
Thank u!
