### ISSUE TITLE
why use"model=self.model"

### ISSUE THREAD

**Issue by HaoliangZhou** [muzairkhattak/PromptSRC#2]
Hi, very nice work Maple and PromptSRC! May I ask why is it necessary to re-instantiate a model (i.e. model=self.model) within the forward_backward function in the promptsrc.py file instead of using self.model directly; and why is it necessary to have both lines Lines 334-335 have both model.load_state_dict(self.previous_model_gpa) and self.model.load_state_dict(self.previous_model_gpa).
Thx!

**Comment by muzairkhattak** [comment]
Hi @HaoliangZhou!

Thank you for showing interest in PromptSRC!

Regarding your first query, please note that our provided PromptSRC code is based on [CoOp repository](https://github.com/KaiyangZhou/CoOp) and they have declared these code lines as it is to possibly make the script compatible with the [Dassl library](https://github.com/KaiyangZhou/Dassl.pytorch) which is used for training the model. So we did not change much the default provided configuration. 

For the second query, the code line of `model.load_state_dict(self.previous_model_gpa)` might be redundant as the model is already updated for the` self.model` variable. You may verify this and then ignore this line incase it does not cause any difference in the results.

Please let us know in-case you have any further questions!
Thank you and kind regards!

**Comment by HaoliangZhou** [comment]
thank you so much!
