### ISSUE TITLE
Can you list the concrete few shot result.

### ISSUE THREAD

**Issue by Zhangwenyao1** [muzairkhattak/PromptSRC#5]

**Comment by muzairkhattak** [comment]
Hi @Zhangwenyao1,

Thank you for showing interest in PromptSRC !

You can find the numerical results for the few-shot setting in the supplementary material of our main paper. Please refer to Table. 13 present in the supplementary material section of the paper. (https://arxiv.org/pdf/2307.06948.pdf)

Let us know incase you face any difficulties! 

Thank you and kind regards!
