### ISSUE TITLE
 Request for Code and Details on "Generalization of PromptSRC towards Video Understanding Tasks"

### ISSUE THREAD

**Issue by SHIBOYA** [muzairkhattak/PromptSRC#7]
I am writing to express my interest in your recent work on "Generalization of PromptSRC towards Video Understanding Tasks" as discussed in your PromptSRC paper. I find this section particularly intriguing and relevant to my research.

I have attempted to replicate the results presented in this section but have encountered some difficulties in reproducing the same outcomes. I believe access to the specific code and additional experimental details might assist in understanding these discrepancies.

Would it be possible for you to share the relevant code and provide more insights into the experimental setup, including any specific configurations or parameters used? 

Your assistance in this matter would be greatly appreciated and would contribute significantly to my research.

Thank you for your time and consideration.

Best regards!

**Comment by muzairkhattak** [comment]
Hi @SHIBOYA,

Thank you for showing interest in PromptSRC.

Regarding your question, please note that the video-based experiments are part of the additional evaluation and analysis of our main paper. Currently, we do not have plans to release code for it. 

We used the official repo of [ViFi-CLIP ](https://github.com/muzairkhattak/ViFi-CLIP) for our video-based experiments. 

Thank you and kind regards!
