### ISSUE TITLE
a quick question about IVLP

### ISSUE THREAD

**Issue by ChushanZhang** [muzairkhattak/PromptSRC#8]
Hello There, 

Thank you for your impressive work! 

I have a quick question. Did you experiment with the MaPLe methods that utilize the deep_compound_prompts strategy (Visual Prompts will interacte to Textual Prompts), instead of relying solely on IVLP? It appears that in the MaPLe paper, you emphasize that the interactive prompt can perform better than IVLP alone. 

Any comments would be appreciated！

**Comment by muzairkhattak** [comment]
Hi @PoopBear1,

Thank you for showing interest in PromptSRC!

Regarding your question, kindly note that we have not experimented PromptSRC framework with MaPLe architecture. The main focus of this study was to address prompt overfitting using regularization, and IVLP was used as the baseline.

However, I believe PromptSRC is compatible with any kind of method (CoOP, CoCoOp, MaPLe, etc.) as it utilizes an optimization approach without altering the architecture of baselines. 

I hope this will be helpful!

Sincerely,
Muhammad Uzair

**Comment by ChushanZhang** [comment]
Thank you for this information!
