### ISSUE TITLE
Where is the code for visual prompt

### ISSUE THREAD

**Issue by meijunhui1998** [muzairkhattak/PromptSRC#9]
Thank you for sharing your great work. 
When I read the code of promptsrc, I only saw that you added prompt to text encode. If possible, please help me point out the location of Visual Prompt, thanks for your guidance

**Comment by muzairkhattak** [comment]
Hi @meijunhui1998,

Thank you for showing interest in PromptSRC! 

Regarding your question, kindly note that the learnable visual prompts are added in `model.py` file [at these lines. ](https://github.com/muzairkhattak/PromptSRC/blob/bb95c77b634d63488f2cad81ff4a72d53bdd06d5/clip/model.py#L406)

For deep prompting, the relevant code is written [here.](https://github.com/muzairkhattak/PromptSRC/blob/bb95c77b634d63488f2cad81ff4a72d53bdd06d5/clip/model.py#L232)

I hope that is helpful!

**Comment by meijunhui1998** [comment]
Thank you very much for your reply. I have another question, where did you add guass and weights? I only saw that you created guass

**Comment by muzairkhattak** [comment]
Hi @meijunhui1998,

The code snippet for aggregating the gaussian weighted prompts can be found [in these lines.](https://github.com/muzairkhattak/PromptSRC/blob/bb95c77b634d63488f2cad81ff4a72d53bdd06d5/trainers/promptsrc.py#L322)

I hope that is helpful! Please let us know if you have any further queries. 

Thank you and kind regards!

**Comment by Outsider-shroud** [comment]
作者，你好，你们上传的代码是不是不完整？
from dassl.utils import setup_logger, set_random_seed, collect_env_info
from dassl.config import get_cfg_default
from dassl.engine import build_trainer

**Comment by Velpro-collab** [comment]
Hello, author, is the code you provided incomplete?
from dassl.utils import setup_logger, set_random_seed, collect_env_info
from dassl.config import get_cfg_default
from dassl.engine import build_trainer

**Comment by muzairkhattak** [comment]
Hi @Outsider-shroud,

Kindly let me know what exact issue are you facing. I believe the code is completed and there are no missing parts.

Make sure you have followed the installation instructions [as shown here.](https://github.com/muzairkhattak/PromptSRC/blob/main/docs/INSTALL.md)

Thank you!

**Comment by Velpro-collab** [comment]
Thank you very much for your reply！
I have another question: The "ResidualAttentionBlock_IVLP" part of the code has altered the structure of the original CLIP model. Can the text and image encoders still use CLIP's pretrained parameters?

**Comment by muzairkhattak** [comment]
Hi @Outsider-shroud,

Yes, the ResidualAttentionBlock_IVLP part of the code still uses the pretrained CLIP parameters.

The only newly initialized components in our framework are learnable prompt vectors, while the rest of all CLIP original modules (like attention layers, FFN layers) use pretrained weights.

**Comment by Velpro-collab** [comment]
Hello, author, could you please indicate where in the code the parameters are added to the group that requires optimization?

**Comment by Velpro-collab** [comment]
Hello, author, should the parameter defined by `self.VPT_shallow = nn.Parameter(ctx_vectors)` be included in the optimizer for updates?

**Comment by muzairkhattak** [comment]
Hi @Velpro-collab,

Regarding your questions, kindly note the following:
- The model parameters are added to the optimizer [at this line in our code.](https://github.com/muzairkhattak/PromptSRC/blob/bb95c77b634d63488f2cad81ff4a72d53bdd06d5/trainers/promptsrc.py#L259)
- For your second question: Yes, the `self.VPT_shallow` is included in the optimizer for updates. Specifically, before sending the model to the optimizer, we first disable the required grad property of all parameters except the visual and textual learnable prompts. That part is implemented [in these lines of code.](https://github.com/muzairkhattak/PromptSRC/blob/bb95c77b634d63488f2cad81ff4a72d53bdd06d5/trainers/promptsrc.py#L233)

**Comment by muzairkhattak** [comment]
Feel free to reopen the issue if there are still any questions.

Thank you and kind regards!
